#define WEBMVCPP_MAJOR_VERSION 0  
#define WEBMVCPP_MINOR_VERSION 4  
#define WEBMVCPP_BUILD_NUMBER 40
 
#define WEBMVCPP_COMPILER_C "cl"  
#define WEBMVCPP_COMPILER_CPP "cl"  
#define WEBMVCPP_LINKER "link"  
