#define WEBMVCPP_MAJOR_VERSION 0
#define WEBMVCPP_MINOR_VERSION 5
#define WEBMVCPP_BUILD_NUMBER 42
#define WEBMVCPP_COMPILER_C "clang"
#define WEBMVCPP_COMPILER_CPP "clang++"
#define WEBMVCPP_LINKER "clang"
